"""Initial migration with all baby data models

Revision ID: 51bb61fc6576
Revises: 
Create Date: 2025-09-20 21:08:30.995323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb61fc6576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baby_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('birth_weight', sa.Float(), nullable=True),
    sa.Column('birth_length', sa.Float(), nullable=True),
    sa.Column('birth_head_circumference', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diaper_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baby_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('has_urine', sa.Boolean(), nullable=True),
    sa.Column('urine_volume', sa.Enum('NONE', 'LIGHT', 'MODERATE', 'HEAVY', name='urinevolume'), nullable=True),
    sa.Column('has_stool', sa.Boolean(), nullable=True),
    sa.Column('stool_consistency', sa.Enum('LIQUID', 'SOFT', 'FORMED', 'HARD', name='stoolconsistency'), nullable=True),
    sa.Column('stool_color', sa.Enum('YELLOW', 'BROWN', 'GREEN', 'RED', 'BLACK', 'OTHER', name='stoolcolor'), nullable=True),
    sa.Column('diaper_type', sa.Enum('DISPOSABLE', 'CLOTH', 'TRAINING', name='diapertype'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['baby_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baby_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('feeding_type', sa.Enum('BREAST', 'BOTTLE', 'SOLID', name='feedingtype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('breast_started', sa.Enum('LEFT', 'RIGHT', name='breastside'), nullable=True),
    sa.Column('left_breast_duration', sa.Integer(), nullable=True),
    sa.Column('right_breast_duration', sa.Integer(), nullable=True),
    sa.Column('volume_offered_ml', sa.Integer(), nullable=True),
    sa.Column('volume_consumed_ml', sa.Integer(), nullable=True),
    sa.Column('formula_type', sa.String(length=100), nullable=True),
    sa.Column('food_items', sa.JSON(), nullable=True),
    sa.Column('appetite', sa.Enum('POOR', 'FAIR', 'GOOD', 'EXCELLENT', name='appetite'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['baby_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growth_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baby_id', sa.UUID(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('head_circumference_cm', sa.Float(), nullable=True),
    sa.Column('measurement_context', sa.Enum('HOME', 'DOCTOR_VISIT', 'HOSPITAL', 'CLINIC', name='measurementcontext'), nullable=True),
    sa.Column('measured_by', sa.String(length=100), nullable=True),
    sa.Column('percentiles', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['baby_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baby_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('VACCINATION', 'ILLNESS', 'MEDICATION', 'MILESTONE', 'DOCTOR_VISIT', 'ALLERGY', 'OTHER', name='healtheventtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('healthcare_provider', sa.String(length=200), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['baby_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baby_id', sa.UUID(), nullable=False),
    sa.Column('sleep_start', sa.DateTime(), nullable=False),
    sa.Column('sleep_end', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_type', sa.Enum('NAP', 'NIGHTTIME', name='sleeptype'), nullable=False),
    sa.Column('location', sa.Enum('CRIB', 'BASSINET', 'PARENT_BED', 'STROLLER', 'CAR_SEAT', 'OTHER', name='sleeplocation'), nullable=True),
    sa.Column('sleep_quality', sa.Enum('RESTLESS', 'FAIR', 'GOOD', 'DEEP', name='sleepquality'), nullable=True),
    sa.Column('sleep_environment', sa.JSON(), nullable=True),
    sa.Column('wake_reason', sa.Enum('NATURAL', 'CRYING', 'FEEDING', 'DIAPER', 'NOISE', 'OTHER', name='wakereason'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['baby_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_sessions')
    op.drop_table('health_events')
    op.drop_table('growth_measurements')
    op.drop_table('feeding_sessions')
    op.drop_table('diaper_events')
    op.drop_table('baby_profiles')
    # ### end Alembic commands ###