"""Remove duration_minutes computed fields from feeding and sleep tables

Revision ID: 749d47acf640
Revises: 51bb61fc6576
Create Date: 2025-10-05 21:44:58.452009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749d47acf640'
down_revision = '51bb61fc6576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeding_sessions', 'duration_minutes')
    op.drop_column('sleep_sessions', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_sessions', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feeding_sessions', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###